// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG6212POE.Data;

#nullable disable

namespace PROG6212POE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROG6212POE.Models.ClaimModel", b =>
                {
                    b.Property<int>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimId");

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AdditionalNotes");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClaimStatus");

                    b.Property<double>("HourlyRate")
                        .HasColumnType("float")
                        .HasColumnName("HourlyRate");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("int")
                        .HasColumnName("HoursWorked");

                    b.Property<string>("SuppDocName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SuppDocName");

                    b.Property<string>("SuppDocPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SuppDocPath");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Title");

                    b.HasKey("ClaimId")
                        .HasName("PK_Claim");

                    b.ToTable("ClaimModel", (string)null);
                });

            modelBuilder.Entity("PROG6212POE.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FirstName");

                    b.Property<int>("HourlyRate")
                        .HasColumnType("int")
                        .HasColumnName("HourlyRate");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<int>("UserRole")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.HasKey("UserId")
                        .HasName("PK_User");

                    b.ToTable("UserModel", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
